on: 
  push:
      branches: [main]

jobs:
  linter:
    runs-on:  [ubuntu-latest]
    defaults:
      run:
        working-directory: ./cinescope
    steps:
      - name: Clone Setup
        uses: actions/checkout@v4

      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.13.7
          cache: true
      
      - run: flutter build apk
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/apk/relase/app-release.apk



      





        

